### ISSUE TITLE
Lỗi chính tả

### ISSUE THREAD

**Issue by uyentramle** [vgmtv/vgm.tv#6]
https://vgm.tv/play/video/04-thieu-nhi.kham-pha-dieu-ky-dieu.nguoi-khon-nguoi-dai

Chỉnh sửa lỗi chính tả của chuyên mục
![11-3-2017 3-58-01 pm](https://user-images.githubusercontent.com/32858733/32366399-831b4332-c0b0-11e7-8c6c-4484054132e4.png)
: Khám Phá Điệu Kỳ Diệu =>>> Khám Phá Điều Kỳ Diệu

**Comment by nampdn** [comment]
Đã sửa!
